import fs from 'node:fs/promises';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {run,session} from '../web/engine.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),catalog=JSON.parse(session('{"op":"catalog"}')).locales;
const cases=[];for(const [locale,methods]of Object.entries(catalog))for(const method of methods)for(const seed of [1,42,987654321])cases.push({locale,method,seed,count:8});
const reference=spawnSync('python',[path.join(root,'tools/reference-locales.py'),path.resolve(process.argv[2])],{input:cases.map(c=>JSON.stringify(c)).join('\n')+'\n',encoding:'utf8',timeout:120000,maxBuffer:20000000});if(reference.status!==0)throw Error(reference.stderr);
const expected=reference.stdout.trim().split('\n').map(JSON.parse);if(expected.length!==cases.length)throw Error('Missing reference results');
const rows=cases.map((c,i)=>{const output=run(JSON.stringify({seed:c.seed,count:c.count,columns:[{name:'value',provider:'localized',locale:c.locale,method:c.method}]}));let actual;try{actual=JSON.parse(output).map(r=>r.value)}catch{actual={error:output}}return {...c,reference:expected[i],actual,match:JSON.stringify(actual)===JSON.stringify(expected[i].values)}});
const report={reference:'Faker 40.39.0',rng:'Explicit xorshift32 Random adapter; Python provider code unchanged. Not default Faker MT19937 seed compatibility.',cases:rows.length,matched:rows.filter(r=>r.match).length,mismatches:rows.filter(r=>!r.match).length,rows};
await fs.writeFile(path.join(root,'evidence/locale-comparison.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({cases:report.cases,matched:report.matched,mismatches:report.mismatches}));
for(const row of rows.filter(r=>!r.match).slice(0,40))console.log(JSON.stringify({locale:row.locale,method:row.method,seed:row.seed,reference:row.reference.error??row.reference.values.slice(0,2),actual:row.actual.slice?.(0,2)??row.actual}));process.exitCode=report.mismatches?1:0;
