const $=id=>document.getElementById(id);let worker,timer,rows=[],headers=[],downloadReady=false;
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function stop(){if(worker){worker.terminate();worker=undefined;}clearTimeout(timer);$('generate').disabled=false;$('run-json').disabled=false;$('cancel').disabled=true;}
function preset(){const locale=$('locale').value,base={seed:Number($('seed').value),count:Number($('count').value)};if($('preset').value==='people')return {...base,columns:[{name:'id',provider:'sequence',start:1,unique:true},{name:'name',provider:'localized',locale,method:'name'},{name:'job',provider:'localized',locale,method:'job'},{name:'city',provider:'localized',locale,method:'city'},{name:'email',provider:'email'}]};return {...base,tables:{products:[{sku:'BOOK-A',title:'旅行手记',price:'38.00'},{sku:'PEN-B',title:'绘图钢笔',price:'62.00'},{sku:'BAG-C',title:'帆布书袋',price:'45.00'}]},schema:{type:'object',fields:[{name:'id',provider:'sequence',start:1001,unique:true},{name:'customer',provider:'localized',locale,method:'name'},{name:'product',type:'foreign',table:'products',path:''},{name:'sku',type:'ref',path:'/product/sku'},{name:'price',type:'ref',path:'/product/price'},{name:'tags',type:'array',min:1,max:3,items:{provider:'choice',values:['new','sample','gift']}}]}};}
function update(){$('job').value=JSON.stringify(preset(),null,2);}
function render(){if(rows.length)headers=Object.keys(rows[0]);const tr=document.createElement('tr');for(const key of headers){const th=document.createElement('th');th.textContent=key;tr.append(th);}$('head').replaceChildren(tr);$('body').replaceChildren();for(const row of rows.slice(0,50)){const tr=document.createElement('tr');for(const key of headers){const td=document.createElement('td'),value=row[key];td.textContent=typeof value==='string'?value:JSON.stringify(value);tr.append(td);}$('body').append(tr);}}
function execute(job){stop();rows=[];headers=(job?.columns??job?.schema?.fields??[]).map(field=>field.name);downloadReady=false;$('save').disabled=true;render();const start=performance.now();worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});$('generate').disabled=true;$('run-json').disabled=true;$('cancel').disabled=false;status('正在生成…');timer=setTimeout(()=>{stop();status('生成超时，请减小数据规模。',true);},30000);worker.onerror=e=>{stop();status('生成失败：'+e.message,true);};worker.onmessage=({data})=>{if(data.rows){rows.push(...data.rows);render();status('已生成 '+rows.length+' 行…');}if(data.error){stop();status('生成失败：'+data.error,true);}else if(data.done){stop();downloadReady=true;$('save').disabled=false;status('已生成 '+rows.length+' 行 · '+headers.length+' 个字段 · '+Math.round(performance.now()-start)+' ms');}};worker.postMessage(job);}
for(const id of ['preset','locale','count','seed'])$(id).onchange=update;
$('generate').onclick=()=>{update();execute(preset());};$('cancel').onclick=()=>{stop();status('已取消，本次数据未完成。');};$('run-json').onclick=()=>{try{execute(JSON.parse($('job').value));}catch(error){downloadReady=false;$('save').disabled=true;status('JSON 错误：'+error.message,true);}};
$('save').onclick=()=>{if(!downloadReady)return;const format=$('format').value,quote=v=>'"'+String(v).replaceAll('"','""')+'"';let data;if(format==='json')data=JSON.stringify(rows,null,2)+'\n';else if(format==='jsonl')data=rows.map(r=>JSON.stringify(r)).join('\n')+(rows.length?'\n':'');else data=[headers.map(quote).join(','),...rows.map(row=>headers.map(key=>quote(row[key]===null?'':typeof row[key]==='string'?row[key]:JSON.stringify(row[key]))).join(','))].join('\r\n')+'\r\n';const blob=new Blob([data],{type:format==='csv'?'text/csv;charset=utf-8':'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='faker-'+rows.length+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
update();execute(preset());
